export const colors = {
  primary: "#6F2DA8",
  secondary: "#F3ECF9",
  black: "#000",
  white: "#fff",
  grey: "#808080",
  textPrimary: "#000",
  textSecondry: "#888",
  red: "red",
  borderColor: "#EBE0F4",
  backgroundPrimary: "#fff",
  tomato: "#FF6347",
  green: "#1CCF23",
  backgroundPrimary: "#DEDEDE",
  orange: "#FFA500",
};
